version: "3"
 
services:
  todo-api-service:
    build:
      context: ./backend
    environment:
      STORAGE: mysql
      MYSQL_HOST: db
      MYSQL_USER: nau
      MYSQL_PWD: ${mysqlpwd}
      MYSQL_DB: ${mysqldb}
    labels:
      - "traefik.http.routers.todo-api-project.rule=Host(`s114431.devops-ap.be`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-api-project.tls=true"
      - "traefik.http.routers.todo-api-project.tls.certresolver=letsencrypt"
    networks:
      - proxy
      - database
 
  frontend:
    image: nginx:1.22
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    labels:
      - "traefik.http.routers.todo-app-project.rule=Host(`s114431.devops-ap.be`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.todo-app-project.tls=true"
      - "traefik.http.routers.todo-app-project.tls.certresolver=letsencrypt"
    networks:
      - proxy
 
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${mysqlpwd}
      MYSQL_DATABASE: ${mysqldb}
      MYSQL_USER: nau
      MYSQL_PASSWORD: ${mysqlpwd}
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - database
 
volumes:
  db-volume:
 
networks:
  proxy:
    external: true
    name: traefik
  database:
